CPROD-1219 call_virtual_responder is namespaced in the virtual_canister_call macro
infinity-swap/canister-sdk pull request #117
Opened 2022-10-10 05:57 UTC by rimbi

2022-10-10 06:40 UTC, Maximkaaa requested changes

2022-10-10 12:36 UTC, rimbi commented on ic-helpers/src/principal/ledger.rs
>  #[cfg(not(target_family = "wasm"))]
good catch, thanks 👍

2022-10-10 12:36 UTC, rimbi commented on ic-canister/ic-canister-macros/src/canister_call.rs
> +            let result = ic_canister::call_virtual_responder(#principal, #method_name, encoded_args)?;
good catch, thanks 👍

2022-10-10 13:08 UTC, Maximkaaa approved these changes

2022-10-11 07:33 UTC, itsyaasir approved these changes

2022-10-12 09:07 UTC, merged