update readme and add more info
infinity-swap/canister-sdk pull request #120
Opened 2022-10-24 07:29 UTC by itsyaasir

2022-10-31 06:28 UTC, F3kilo requested changes

2022-10-31 06:28 UTC, F3kilo commented on Cargo.toml
> +    "ic-stable-storage",
There is no `ic-stable-storage` package in the workspace now. But the `ic-stable-structures` is present.

2022-10-31 06:28 UTC, F3kilo commented on Cargo.toml
> +    "ic-stable-storage",
Already fixed)

2022-10-31 06:28 UTC, F3kilo approved these changes

2022-11-01 09:19 UTC, Maximkaaa approved these changes

2022-11-01 09:20 UTC, merged