Add the necessary deriving instances for CandidHeader
infinity-swap/canister-sdk pull request #95
Opened 2022-09-05 12:10 UTC by awkure

2022-09-05 12:26 UTC, Maximkaaa approved these changes

2022-09-06 08:04 UTC, hagsteel requested changes

2022-09-06 08:04 UTC, hagsteel commented on ic-helpers/src/candid_header.rs
> +#[derive(Debug, CandidType, Deserialize, Clone, PartialEq)]
Add `Eq` as well, because all underlying types implement `Eq`

```suggestion
#[derive(Debug, CandidType, Deserialize, Clone, PartialEq, Eq)]
```

2022-09-06 08:58 UTC, hagsteel approved these changes

2022-09-06 09:01 UTC, merged