Fix clippy warnings
infinity-swap/canister-sdk pull request #99
Opened 2022-09-13 05:57 UTC by hagsteel

Merge CPROD-1165-be-do-not-add-methods-to-idl-if-no-api-feature-is-used first, these are just clippy fixes

2022-09-13 07:59 UTC, awkure approved these changes

2022-09-13 08:53 UTC, itsyaasir approved these changes

2022-09-13 11:26 UTC, awkure requested changes

2022-09-13 11:26 UTC, awkure commented on ic-canister/ic-canister-macros/src/api.rs
> +                if !cfg!(feature = "no_api") || (#name != "burn" && #name != "mint") {
👀

2022-09-21 17:59 UTC, itsyaasir commented
I think we can close this PR @hagsteel

2022-09-22 06:02 UTC, hagsteel commented
> I think we can close this PR @hagsteel

Closing this, assuming from the comments that this has already been taken care of?

2022-09-22 06:02 UTC, closed without merging